# Generated by Django 5.1 on 2024-08-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('login_password', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization', models.CharField(max_length=255)),
                ('ph_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(upload_to='media/users')),
                ('super_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField()),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MainApp.staff')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
    ]
